version: "2.2"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    env_file:
      - .env
    ports:     
      - 27017:27017
    environment:     
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - .env
    ports:     
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
    depends_on:
      - mongo
  library:
    build:
      context: .
    command: npm run start
    volumes:
      - ".:/app/"
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - DB_USERNAME=${MONGO_USER}
      - DB_PASSWORD=${MONGO_PASSWORD}
      - DB_NAME=${MONGO_DB_NAME}
      - DB_HOST=${MONGO_CONNECT_URL}
    links:
      - mongo
    depends_on:
      - mongo